services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    # image: node:lts-bookworm
    ports:
      - 3000:3000
    volumes:
      - ../..:/workspaces:cached
    network_mode: 'host'
    command: sleep infinity
